name: GitHub-Actions-Terraform-Azure-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      RESOURCE_GROUP: 'amit-rg'
      STORAGE_ACCOUNT: 'amitstgtf'
      CONTAINER_NAME: 'tfstate'
    
    runs-on: ubuntu-latest
  
    defaults:
      run:
        shell: bash
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
  
      - name: Initialize Terraform
        run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"
  
      - name: Plan Terraform
        run: terraform plan -out=tfplan
  
      - name: Apply Terraform
        run: terraform apply tfplan -auto-approve
