name: GitHub-Actions-Terraform-Azure-Pipeline

# on:
#   push:
#     branches:
#     - main
#   pull_request:
#     branches:
#     - main

# manual trigger
on: workflow_dispatch

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  build:
    name: 'Terraform Init, Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
  
      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate
  
      - name: Plan Terraform
        run: terraform plan -out=tfplan
  
      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan

      # - name: Destroy Terraform
      #   run: terraform destroy -auto-approve
